# Site settings
title: Mike Pfister
email: pfista@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Technical ramblings etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelpfister.com" # the base hostname & protocol for your site
twitter_username: pfista
github_username: pfista 
linkedin_url: "https://www.linkedin.com/in/mikepfister"
linkedin_name: "LinkedIn"
vimeo_url: "https://vimeo.com/pfista"

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap
